### ISSUE TITLE
Problem with VeinMining grass with hand

### ISSUE THREAD

**Issue by ghost** [2008Choco/VeinMiner#10]
```
Hand:
    - 'minecraft:grass'
```

When I add that, and somebody VeinMines grass or tall grass, it gives me the error in [this hastebin](https://hastebin.com/ukatusoyov.cs), and it doesn't actually break additional grass nearby until 30-60 seconds later. Any reason this might be?

I am using PaperSpigot 1.13

**Comment by 2008Choco** [comment]
This is just me being negligent with durability. This is an easy fix. I fully expect to have another build of VeinMiner by tomorrow evening.

**Comment by AshtonMemer** [comment]
> This is just me being negligent with durability. This is an easy fix. I fully expect to have another build of VeinMiner by tomorrow evening.

Haha I understand. Thanks, looking forward to the new build.
