### ISSUE TITLE
Grass renamed in newer versions...

### ISSUE THREAD

**Issue by PaladinFallen** [2008Choco/VeinMiner#105]
[22:06:51] [Server thread/INFO]: [VeinMiner] Unknown or invalid block state string for input: "minecraft:grass". Is it an item?

**Comment by 2008Choco** [comment]
The default config as a whole probably just needs an update for modern versions. I'm sure there are some blocks that were added and/or changed that need updating.

**Comment by 2008Choco** [comment]
Forgot to link it, but it has been updated to `short_grass` in [afd60a6f34ebdf4219a2cd926528cf29a9de990d](https://github.com/2008Choco/VeinMiner/commit/afd60a6f34ebdf4219a2cd926528cf29a9de990d)
