### ISSUE TITLE
Console error in anticheat

### ISSUE THREAD

**Issue by vxkShelby** [2008Choco/VeinMiner#110]
09.03 12:07:12 [Server] INFO [VeinMiner] Enabling VeinMiner v2.1.1
09.03 12:07:12 [Server] INFO [VeinMiner] Using SQLITE for persistent storage.
09.03 12:07:12 [Server] INFO [VeinMiner] Loading configuration options to local memory
09.03 12:07:12 [Server] INFO [VeinMiner] Added 13 aliases.
09.03 12:07:12 [Server] INFO [VeinMiner] Registered category with id "Axe" holding 6 unique items and 26 unique blocks.
09.03 12:07:12 [Server] INFO [VeinMiner] Registered category with id "Hoe" holding 6 unique items and 10 unique blocks.
09.03 12:07:12 [Server] INFO [VeinMiner] Registered category with id "Pickaxe" holding 6 unique items and 23 unique blocks.
09.03 12:07:12 [Server] INFO [VeinMiner] Registered category with id "Shears" holding 1 unique items and 27 unique blocks.
09.03 12:07:12 [Server] INFO [VeinMiner] Registered category with id "Shovel" holding 6 unique items and 10 unique blocks.
09.03 12:07:12 [Server] INFO [VeinMiner] Registering commands
09.03 12:07:12 [Server] INFO [VeinMiner] Performing an update check!
09.03 12:07:12 [Server] INFO [VeinMiner] Anti cheat detected. Enabling anti cheat support for "GrimAC"
09.03 12:07:12 [Server] ERROR [VeinMiner] Failed to register events for class wtf.choco.veinminer.anticheat.AntiCheatHookGrim because ac/grim/grimac/events/FlagEvent does not exist.
09.03 12:07:12 [Server] INFO [VeinMiner] Anti cheat detected. Enabling anti cheat support for "Spartan"
09.03 12:07:12 [Server] INFO [VeinMiner] Registering events
09.03 12:07:12 [Server] INFO [PlaceholderAPI] Successfully registered internal expansion: veinminer [2.1.1]
09.03 12:07:12 [Server] INFO [VeinMiner] Vault found. Attempting to enable economy support...
09.03 12:07:12 [Server] INFO [VeinMiner] Economy found! Hooked successfully.
09.03 12:07:12 [Server] INFO [VeinMiner] Enabling Plugin Metrics
09.03 12:07:12 [Server] INFO [VeinMiner] Thanks for enabling Metrics! The anonymous stats are appreciated
09.03 12:07:12 [Server] INFO [VeinMiner] You are on the latest version of VeinMiner.

**Comment by 2008Choco** [comment]
This was fixed in a recent version of VeinMiner. You'll have to update to [VeinMiner 2.2.4](https://www.spigotmc.org/resources/veinminer.12038/update?update=535677).
