### ISSUE TITLE
Companion stops veinminer plugin working

### ISSUE THREAD

**Issue by SmellyPjs** [2008Choco/VeinMiner#113]
Upon installing the Veinminer Companion fabric mod (1.20.6), the veinminer plugin on my paper server (1.20.6) stopped working for me. Worked for others fine by crouching but neither my set keybind or crouching worked for me.

**Comment by zqilz** [comment]
I also have a similar problem
The difference is that mine shuts down randomly, maybe an hour or so after launching the client. The only solution I've found is to relaunch the client

**Comment by 2008Choco** [comment]
The only two reasons I know why the client would stop working during the server's runtime are:
1. You don't have `/veinminer mode client` selected
  a. This is usually done automatically when you join with the client, so if this isn't the case, then it would have had to have been changed at some point by mistake
2. The server was reloaded with Bukkit's `/reload` command. The server loses the state of all players using the client which is pretty difficult to solve

The only other exception would be that maybe either the server is running an outdated version of VeinMiner and doesn't support the 1.20.6 protocol (but there are version checks, so you would probably know) or your client mod is outdated (also unlikely). Beyond that, I've not experienced this issue at all. I have the client mod installed 24/7 and any time I test something locally I'm testing with the client mod. The above two scenarios are the only two in which I know it would ever stop working inexplicably.

**Comment by 2008Choco** [comment]
I had an opportunity to test this again as I was doing some updating and can confirm that the vein miner client does, in fact, still work as expected on 1.21. Please see the above comment and make sure you have both the server and client configured correctly.
