### ISSUE TITLE
Upgraded to 2.2.4 from a previous version

### ISSUE THREAD

**Issue by mmazur519** [2008Choco/VeinMiner#114]
I upgraded from a previous version to 2.2.4 but all of the commit changes from [20adbc8](https://github.com/2008Choco/VeinMiner/commit/20adbc81cf6fc3a073a62c5200b99d8fd45aed50) when you added cherry tree's when I updated it didn't update the config.yml on upgrade so it was not harvesting. I manually made changes to the config.yml and categories.yml and now it is working with cherry trees. Don't know if you can check the version of the config.yml and update or append the files as required when there is a new version.

**Comment by 2008Choco** [comment]
I'm hesitant to edit block lists when adding new entries to the default config.yml. There are some people that use VeinMiner as a replacement for tree feller plugins and so adding things like `minecraft:nether_quartz_ore` to their pickaxe's block list automatically would be rather annoying. This is the reason I put the default config.yml on Spigot's resource description page (and I suppose it being available on GitHub), for those that want to quickly reference what is a default setting.

**Comment by mmazur519** [comment]
Thanks, for the reply didn't fully understand the use case but makes sense. Since new block additions are infrequent the manual updating what is needed isn't an issue now that I have realized it.

**Comment by mmazur519** [comment]
Resolved
