### ISSUE TITLE
"You are not allowed to vein mine here"

### ISSUE THREAD

**Issue by Joeslinky** [2008Choco/VeinMiner#115]
Is there some permission or setting I'm missing to allow vein mining globally?

Version: 1.20.6
Plugin list:

BisectHosting-bukkit-1.6+.jar
Clearlag.jar
CoreProtect-22.4.jar
CraftingStore.jar
DarkerNights-2.7.1.jar
DeadlyDisastersPRO-V14.3.jar
DecentHolograms-2.8.8.jar
DiscordSRV-Build-1.27.0.jar
Dynmap-3.7-beta-5-spigot.jar
EssentialsX-2.20.1.jar
EssentialsXSpawn-2.20.1.jar
FastAsyncWorldEdit-Bukkit-2.10.0.jar
GraveStonesPlus.jar
GriefPrevention.jar
LPC.jar		Installed	Remove
LuckPerms-Bukkit-5.4.131.jar
multiverse-core-4.3.12.jar
multiverse-inventories-4.2.6.jar
multiverse-portals-4.2.3.jar
NoCheatPlus.jar
openaudiomc-6.10.1.jar
orebfuscator-plugin-5.4.4.jar
PlaceholderAPI-2.11.6.jar
PlugManX-2.4.0.jar
ProtocolLib.jar
RealisticSeasons-10.8.1.jar
smoothtimber-legacy-1.27.0.jar
spark-1.10.67-bukkit.jar
Vault.jar
veinminer-bukkit-2.2.4.jar
\worldguard-bukkit-7.0.9-dist.jar

**Comment by 2008Choco** [comment]
That message is sent by VeinMiner's WorldGuard integration. You may have to explicitly enable the `vein-miner` flag in the region (or the `__global__` region)
