### ISSUE TITLE
Command to directly toggle on/off cmd for players

### ISSUE THREAD

**Issue by bobhenl** [2008Choco/VeinMiner#121]
Hello, could you please add way to toggle veinminer on/off directly for players, when their rank expire?

Like /veinminer on/off <player>, or support player argument in other commands too

**Comment by 2008Choco** [comment]
I think ideally this should be done with permissions, no? You should be able to give your rank the `veinminer.veinmine.*` permission (or any of its children) to the special rank and revoke it from the default group.

**Comment by 2008Choco** [comment]
Yes. That vein mining permission allows them to actually _use_ vein miner regardless of its enabled state. `veinminer.command.toggle` is what allows them to toggle it on and off. Just note that `veinminer.veinmine.*` is default for all players so if you want to remove it, you'll have to negate it in your base group and re-add it to whichever group you want to have it.

**Comment by bobhenl** [comment]
OK, thanks so much! I believe it's solved now
