### ISSUE TITLE
Client Mod breaking Block issue

### ISSUE THREAD

**Issue by Zoriot** [2008Choco/VeinMiner#123]
There is a random delay when using the latest beta version of the Companion mod. Doesnt matter if i set the mode to the mod or not. 
I only use it with that other mods: https://modrinth.com/modpack/kami-chan-optimized-plus/version/9.0.1.0

**Comment by 2008Choco** [comment]
How much of a delay are we talking? There may be a delay within 5 - 50ms or so (ideally less) but the outlining has to be calculated by the server, so the client has to make a request then wait for a response before outlining anything. If your internet or connection to the server is unstable or slow, you'll definitely notice that delay a lot more.

**Comment by Zoriot** [comment]
Thanks for the information. Yea seems like it was my internet connection. At least the delay (1-10 seconds) was gone yesterday. Is it possible to disable that rendering for a player?

**Comment by 2008Choco** [comment]
You can disable it for players, yes. There's a permission for it. `veinminer.client.wireframe`. It's enabled by default so you'll have to negate it on the player who you want to remove it from. Alternatively you can disable it all together for all players in the config under `config.yml`'s `Client.AllowWireframeRendering`.

**Comment by Zoriot** [comment]
Okay. Can you also release the Mod to modrinth? Would be great

**Comment by 2008Choco** [comment]
A few people have asked me to do this. Maybe. We'll see.
