### ISSUE TITLE
Error with BlockBreakEvent

### ISSUE THREAD

**Issue by Dungjava** [2008Choco/VeinMiner#124]
I just use zessential and i got error from veinminer after break block + spam console
Error: https://mclo.gs/y3pa1IR
Full log: https://mclo.gs/G4meuSj
Server version: Leaf 1.21.1
Java 22
Veinminer 2.2.5

**Comment by 2008Choco** [comment]
This may be an issue with zEssentials instead. VeinMiner isn't doing anything special. It's just calling upon Vault's economy services, which VM is doing successfully. The exception is in zEssentials' Vault service implementation.

**Comment by Dungjava** [comment]
Hello sorry for late. The author say that he just fixed, thanks for your help
