### ISSUE TITLE
Veinminer not working on redstone ore

### ISSUE THREAD

**Issue by VallaAzura** [2008Choco/VeinMiner#15]
It is not veinmining redstone ore. have tried adding it to the list, in which it states it is already on the list. every other ore works. running latest version in a plain vanilla server

Edit: After doing some more testing, i found that if you smack the redstone, all adjacent lit redstone will also be veinmined, therefore it is just not working on unit redstone nor a mixture of the both.

**Comment by 2008Choco** [comment]
Known issue, still yet to find a solution to it. This seems to be the case for any stated block. i.e. when `minecraft:log` is added to the block list, it will only vein mine blocks of similar states even though a state was not specified.
