### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by UnofficialAshton** [2008Choco/VeinMiner#19]
I would like only a specific group to have access to VeinMiner. For instance, I give the default group `-veinminer.veinmine.*`, and I would give group 2 access to veinminer by adding `veinminer.veinmine.*`, but it is inheriting the other commands as well, and that seems to still disallow VeinMiner from being used. What can I do?

**Comment by DualKeysCeo** [comment]
If you only want a specific group to access `veinminer.veinmine.*` why are you giving it to default?

**Comment by UnofficialAshton** [comment]
You’re misunderstanding, but it doesn’t matter, I figured out a workaround.
