### ISSUE TITLE
Not support CoreProtect

### ISSUE THREAD

**Issue by Ghost-chu** [2008Choco/VeinMiner#2]
VeinMiner breaked blocks cannot log in the coreprotect break log.

**Comment by 2008Choco** [comment]
What version of VeinMiner are you using? 1.11.3 or 1.12.0? Going to need a little bit more information than that.

**Comment by Ghost-chu** [comment]
1.11.3 on Minecraft 1.13
CoreProtect can't track use VeinMiner breaked block,

**Comment by 2008Choco** [comment]
VeinMiner 1.11.3 does not support Minecraft 1.13. There is a beta build of VeinMiner, 1.12.0, that supports Minecraft 1.13 but may not work perfectly. If you wish to run that version, it is advised that you do so with caution.

**Comment by Ghost-chu** [comment]
test on lastet dev version,Not support.
You can use CoreProtect API or new a BlockBreakEvent to make CoreProtect log player action.

**Comment by 2008Choco** [comment]
I do use a BlockBreakEvent. It's called internally.

**Comment by Ghost-chu** [comment]
I try lastet version,It still not support CoreProtect,Player breaked the block but coreprotect no any logs
