### ISSUE TITLE
Problem with too many drops

### ISSUE THREAD

**Issue by KisaragiEffective** [2008Choco/VeinMiner#31]
when I digged a lapislazuli stack (20 ores) with fortune 3, I got nothing.
I doubt overflowed somewhere :thinking:

**Comment by 2008Choco** [comment]
Very old issue but I can assure you that VeinMiner does not modify the stacks that are dropped. It calls upon vanilla block-breaking functionality. If drops are not being created properly, it is at the fault of another plugin.
