### ISSUE TITLE
Sliding when breaking tower of blocks

### ISSUE THREAD

**Issue by Decio-Greenwood** [2008Choco/VeinMiner#32]
When breaking blocks from a 1 wide tower whilst standing on it causes sliding if tool is too efficient. This occurs when breaking 1 block at a time, and seems to be due to lag between block breaking and player fall.

I know this is occurring due to the plugin as it only happens when the plugin is enabled.

Thanks.

(Great plugin with good customisation options btw!)

**Comment by 2008Choco** [comment]
Very old issue though I don't notice this being the case on a test server - closing as it is not relevant to VeinMiner.
