### ISSUE TITLE
onBlockBreak is called once more than necessary.

### ISSUE THREAD

**Issue by mhmyesman** [2008Choco/VeinMiner#36]
VeinMiner calls PlayerVeinMineEvent (PVME) after onBlockBreak (oBB) is called. 

VeinMiner calls oBB once for every block in the vein, disregarding the initial oBB call: VeinMiner calls oBB as if one block _hasn't been broken_ already. This looks like a bug.

Pretty high chance I make a wrong assumption about the inner workings while using improper terminology -- forgive me.

Anyway, here is the bug how I observed it:

https://www.youtube.com/watch?v=HfpT-ZlBw_4&feature=youtu.be

Tested by sending message to player on PVME and oBB execute.

**Comment by 2008Choco** [comment]
You're right. I know exactly why this is happening. I'm not sure it will have caused too many issues but this may be a potential duplication glitch if used in unison with other plugins that trigger additional block drops. Thank you for the detailed report.
