### ISSUE TITLE
Using /vm Toggle does not toggle off.

### ISSUE THREAD

**Issue by HippHamster** [2008Choco/VeinMiner#38]
Addittioanlly, It is set to sneak in the config and it is always active.

**Comment by 2008Choco** [comment]
Based on your comment in #37, is VeinMiner even enabling on your server? Do you have any errors on startup that may be preventing VeinMiner from starting? Are you also certain that you have permission to use VeinMiner, are using the correct tools and have everything configured properly? Changing `ActivationMode` to `ActivationStrategy` should most definitely resolve the issue.

**Comment by HippHamster** [comment]
The problem I am having it thaat vein miner is always on. without sneak. No one can toggle it off. We try and it says in that that it is off, but it continues to break multiple blocks.

**Comment by 2008Choco** [comment]
I cannot confirm this. Opened a test world just now, assigned `ActivationStrategy` to `ALWAYS` (as well as `SNEAK`), used `/veinminer toggle` (and `/veinminer toggle pickaxe` just to be certain) and everything worked as expected. Do note that `/veinminer toggle` is NOT persistent across server restarts. It has to be disabled again after another restart.

May I see your config.yml

**Comment by HippHamster** [comment]
Please close this thred. The issue was being cause by another larger addon 'FaastSurvival'. sorry for any inconvinece caused.
