### ISSUE TITLE
Categories of same tool types cancelling each other out

### ISSUE THREAD

**Issue by CamoWisp** [2008Choco/VeinMiner#41]
I am unsure if this is intentional, however it seems when trying to create new categories with similar tools that allow you to break more blocks than the other category of the same tool types, it cancels out.

For example; one rank has the default pickaxe category that allows them to veinmine ores with all pickaxe types. The next rank up has a special pickaxes category that allows them to vein mine stone, with all pickaxe types, with a vein size of 16. However when attempting to veinmine ores as the higher rank, ores are no longer able to be veinmined, despite having proper permission. If I were to add the ores to the special pickaxes category, the lower rank would no longer be able to veinmine the ores despite having permission and the ores being set in the regular pickaxe category.

This has stirred me crazy a little bit as I wanted to give my highest rank the ability to veinmine trees and many other blocks from different categories, while the lower ranks only have the simpler blocks to veinmine. All to no avail.

**Comment by 2008Choco** [comment]
I suppose the most common denominator would be selected... this is a situation I had not really accounted for. I'm not sure exactly how this could be accomplished as it's a very niche case-scenario.

**Comment by 2008Choco** [comment]
Forgot to mention this in the commit, but resolved in [46c8b6f](https://github.com/2008Choco/VeinMiner/commit/46c8b6f4f25b7d7ad8d5a3605e5aafd6ad53dd11) with a new `Priority` option in categories which will be available in VeinMiner 2.0.0
