### ISSUE TITLE
NoCheatPlus support

### ISSUE THREAD

**Issue by EnTIv** [2008Choco/VeinMiner#42]
![image](https://user-images.githubusercontent.com/38716516/89963444-387c1c00-dc7a-11ea-93b8-20d853604237.png)
https://www.mc-market.org/resources/475/

**Comment by 2008Choco** [comment]
NoCheatPlus is definitely supported. At least the version developed by the original authors. The one you are using is a modified fork which must make changes to where VeinMiner does not recognize it. In which case it's something you should bring to the attention of the developer of the anti cheat. I've done my part, I've implemented the necessary means of support, the fork should be maintaining that compatibility.

Not to mention I see no free public-facing API I can depend against... all the more reason for me not to explicitly support it. I'm not spending $7.50 to support a lesser-known fork for just a server or two.

**Comment by EnTIv** [comment]
Thank you! I found it: https://dev.bukkit.org/projects/compatnocheatplus-cncp
