### ISSUE TITLE
/veinminer toggle doesn't work for anything besides axe

### ISSUE THREAD

**Issue by Lucinafailure** [2008Choco/VeinMiner#43]
Im on a 1.16.1 server and I can't toggle it off on anything besides axe

**Comment by Lucinafailure** [comment]
update: I just realize can toggle every tool by just not specifying a tool, but gonna keep this here so the bug can get a fix

**Comment by DXUltimate** [comment]
I think it might help if you provide additional information on this, such as configuration, version of spigot/paper/whatever, what permissions you're using, Even a plugin version is necessary to actually fix these kinds of issues. =3

I've tested this with the latest version to see what you were talking about, and the toggle function appears to be normal as op, as well as a user with the permissions, with the base configurations.

**Comment by 2008Choco** [comment]
Cannot replicate in modern versions. If this issue is still present, please open a new issue
