### ISSUE TITLE
veinminer and luck perms is not compatible it seams 

### ISSUE THREAD

**Issue by broken1arrow** [2008Choco/VeinMiner#45]
I have not set any player perms or group perms, but by default all perms is on true. 

luck perms version 5.1.93
https://luckperms.net/verbose/YruRTYJpWn

veinminer 16.2

papermc 1.16.2 184

**Comment by 2008Choco** [comment]
This is just how VeinMiner works. Most permissions are given by default. If you wish to revoke vein mining permissions from players or groups, you can set the permission to `false`.

**Comment by broken1arrow** [comment]
> 
> 
> This is just how VeinMiner works. Most permissions are given by default. If you wish to revoke vein mining permissions from players or groups, you can set the permission to `false`.

@2008Choco 

I got a lot of help from luck perms.

it's so that my old prem plugin blocks all perms. even the ones you get defult.

But I have a suggestion, players get suggestions for all the different tools and can turn on and off these.

Of course, only the tools for which they have a premium work.

But it is unnecessary for players to be able to touch the others as well.

Add a binder eg veinminer.mode.pickaxe veinminer.mode.axe etc.
