### ISSUE TITLE
Add option to decrease the food bar

### ISSUE THREAD

**Issue by Zegameus** [2008Choco/VeinMiner#46]
In my server I have made a system of professions and the group of miners gave me the idea to add this plugin, based on a datapack of the same name. But in the plugin there is no option that allows you to spend thighs (food), when you use the plugin to break many blocks. 

So, I ask you please, in the next update, if you can, to add an option in the configuration where you can choose how many thighs you get when you perform an action.

Thanks in advance.

**Comment by 2008Choco** [comment]
This has been available in VeinMiner as of version 1.16.0. Download the latest version [on Spigot](https://www.spigotmc.org/resources/veinminer.12038/update?update=356114) and see the default configuration file for information regarding hunger depletion.
