### ISSUE TITLE
Can't add tools from mods

### ISSUE THREAD

**Issue by KuhPik** [2008Choco/VeinMiner#49]
Yeah i know that plugins commonly doesnt work with a mods. But there is a buch of workarrounds and mine is working perfectly fine. I did successefully added ores to the... list. But can't do the same with tools.

Server used : https://github.com/IzzelAliz/Arclight
Issue with mod : https://www.curseforge.com/minecraft/mc-mods/ores-above-diamonds

And i guess other modded tools will not work too.

**Comment by 2008Choco** [comment]
My stance on the use of VeinMiner on modded servers has always been this - why? Presumably if you're running on a Forge-based server, you should have the option to instead be using something such as VeinMiner (for Forge) or OreExcavator depending on which version you're running. These are mods written against Forge with the intent of supporting modded blocks and items. VeinMiner for Bukkit never had that intent and I apologize but it's not something I'm going to invest time attempting to fix.
