### ISSUE TITLE
 [VeinMiner4Bukkit] Darkens other mod UI's while active

### ISSUE THREAD

**Issue by milkev** [2008Choco/VeinMiner#54]
parts of other mod UI's, such as voxelmap's minimap, or optifines fps display, are darkened considerably while the key is held down.
tested with and without optifine/other performance enhancing mods.
the server im testing on has not yet updated to the new version of veinminer that allows this feature to be used, i dont know if that plays in a role in it or not. (i dont imagine it does, since this mod is pretty much only client side, but you never know)
edit: forgot to attach images
![2021-01-30_20 19 09](https://user-images.githubusercontent.com/22010128/106373611-87a52e80-6338-11eb-967a-6c972f2e3fce.png)
![2021-01-30_20 19 11](https://user-images.githubusercontent.com/22010128/106373612-88d65b80-6338-11eb-9899-20ccc5e96797.png)

**Comment by 2008Choco** [comment]
Oop, I think I might know why too. I'm going to chalk that up to my noviceness when it comes to rendering 😛 I will get this fixed for the next release!
