### ISSUE TITLE
[Request] Placeholders

### ISSUE THREAD

**Issue by mercurialmusic** [2008Choco/VeinMiner#56]
My apologies if this isn't the correct place for this, but a nice QOL thing, if you feel like it, would be placeholders and PlaceholderAPI support. In my mind these would primarily focus on the toggles, returning true or false whether they have VeinMiner toggled. 

I would plan to use this in an interactive hologram that would inform them of their current state and allow them to click on it to toggle (I'm already able to do that, just not able to tell them the current status). 

Thanks for the consideration!

**Comment by 2008Choco** [comment]
Yeah, certainly. Honestly placeholders are something I want to start integrating into more of my plugins I was just never certain what all could be useful in VeinMiner. Togglability state makes sense to me.
