### ISSUE TITLE
[Bug] VeinMiner thinks it's 1.17.5 even tho it's 1.17.6

### ISSUE THREAD

**Issue by X1nto** [2008Choco/VeinMiner#57]
Yesterday I downloaded VeinMiner from SpigotMC (which redirects to the GitHub releases page). The filename and the release tag both say it's 1.17.6 but in the console, I get `[VeinMiner] An update is available! VeinMiner 1.17.6 may be downloaded on SpigotMC` message. looking into the JAR's plugin.yml it seems like the version is set to 1.17.5:
![image](https://user-images.githubusercontent.com/48173186/115950107-5b89eb80-a4ea-11eb-9ad2-ad34b34d9485.png)

**Comment by Craftmaster657** [comment]
you have to run the command: /veinminer:vm mode and then any or sneak or somthing it worked for me

**Comment by omega9380** [comment]
You can open the JAR as a ZIP file using 7Zip, edit plugin.yml at the top to 1.17.6, then save it, thats a quick workaround for the "update available" message until the release is updated here.
Seems to be a common miss, this is at least the third time I've updated VM to the new version where the wrong version number was listed in plugin.yml :)
