### ISSUE TITLE
Minor issue: Default config is not adding powered snow to config.yml

### ISSUE THREAD

**Issue by omega9380** [2008Choco/VeinMiner#61]
When the default config is generated it is unable to add powdered snow to the blocklist for the shovel.

The reason is you are trying to add `minecraft:powdered_snow`, the namespace ID for powdered snow is `minecraft:powder_snow`.

Along the same lines, you missed deepslate redstone ore on the default config.

Minor issue, we can just add powdered snow and the ore manually, but I wanted to let you know!

**Comment by 2008Choco** [comment]
Thank you! Minor oversights on my part. Will adjust but won't publish a release for it as it's relatively minor.
