### ISSUE TITLE
Veinminer doesn't Veinmine

### ISSUE THREAD

**Issue by Crashb0y01** [2008Choco/VeinMiner#62]
I added vein miner to my 1.17 server I gave everyone the permissions veinminer.client, veinminer.mode, veinminer.toggle, and veinminer.veinmine. at first I installed the fabric mod to allow me to use a custom key bind with vein miner and every time I hit that key bind my game would just crash, so I removed the fabric mod and tried the SNEAK and then ALWAYS activation modes instead and it simply doesn't vein mine. I do have other plugins on the server (Inventory Rollback, ImageMaps, UberEnchant, Sleep-most, Viaversion, Luckperms, Vault, dynmap, WorldEdit, WorldGuard, Core Protect, and The full EssentialsX set of plugins) i used these same plugins on my 1.16 server with vein miner and had no issues though so I have no reason to think those would be the reason for this issue.

**Comment by Crashb0y01** [comment]
Disregard my last comment, updating to spigot build 3133 fixes it, I was previously using spigot build 3100 and it didn't work on that.

**Comment by 2008Choco** [comment]
The client mod still requires an update, but yeah I use some newer API in 1.17 😄
