### ISSUE TITLE
Hook ItemsAdder

### ISSUE THREAD

**Issue by Tylwen** [2008Choco/VeinMiner#68]
Hello,

Will it be possible to add a hook for ItemsAdder so that it works with custom ores?
https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8custom-items-huds-guis-mobs-3dmodels-emojis-blocks-wings-hats-liquids.73355/

Regards,

**Comment by 2008Choco** [comment]
I don't have any plans on adding support for ItemsAdder. Sorry :(
