### ISSUE TITLE
[Feature Request] Option to set as disabled by default/Hot-key only mode

### ISSUE THREAD

**Issue by StuffOfSonny** [2008Choco/VeinMiner#74]
Long story short, I run a server with Geyser enabled, to let my friends play from either their PCs or mobile devices (Android/iOS/Switch, and consoles would work too). I completely understand that there's not much accommodation that can be made for Bedrock players.
One player was building an elevated structure, and misplaced a log, and when they went to break it, it collapsed the whole thing since activation was set to sneak. I made the compromise to not define an activation method in the config.yaml, in the hopes that this would disable Veinminer, unless they had the companion mod to set it to a dedicated hotkey.
This did not work.
I ask that maybe this could be implemented, and a work-around.

**Comment by 2008Choco** [comment]
Yeah absolutely. I don't see why not. I'll add a `NEVER` option in the next release :)
