### ISSUE TITLE
Blocks detroyed but not dropping when tool breaks

### ISSUE THREAD

**Issue by FrederikTheDane** [2008Choco/VeinMiner#8]
I have a problem where if i use, say, a pickaxe with 2 durability left to mine, say, 4 blocks of ore, the whole vein will dissapear but only drop 2 items, and the other will vanish into thin air as if they were broken by hand.

To reproduce:
/give @s minecraft:iron_pickaxe{Damage:248}
Place more than 3 blocks of an ore
Crouch and mine the ores
3 ores/items will drop, but all the other ore blocks will vanish

I hope you will look into this. Other than this issue, the plugin works like a charm! :-) Thanks in advance

**Comment by 2008Choco** [comment]
Are you on the most recent version of VeinMiner (1.12.2)? If so, this may have to do with the changes to durability in Minecraft 1.13. I'll take a look. If you're not using the latest, please update and see if the issue still occurs because of a change to how durability works was made in 1.12.2

**Comment by FrederikTheDane** [comment]
Oh my bad! I'm on VeinMiner 1.12.2, Minecraft version 1.13.1 and Spigot 1.13.1 \#1898 (git-Spigot-f6a273b-1cf8b5d)

**Comment by 2008Choco** [comment]
Alright, I've been able to reproduce this in the latest version (appreciate the steps to reproduce). Thank you. I will take a look.
