### ISSUE TITLE
Get a created item

### ISSUE THREAD

**Issue by Chypik** [2008Choco/VeinMiner#80]
good afternoon.
I can't figure out how to give the player created items from a similar category?

```
ExampleCategory:
 MaxVeinSize: 10
  Items:
   - 'minecraft:torch'
   - 'minecraft:redstone_torch':
 Name: "&6 My Cool Torch!"
 Lore:
  - "First line!"
  - "&# - "&second line!"
```

**Comment by Chypik** [comment]
no money is withdrawn from the player:
RepairFriendlyVeinminer: false
IncludeEdges: true
MaxVeinSize: 32
Cost: 100.0
----------------------
Paper version git-Paper-323 (MC: 1.18.2)
[Vault] Enabling Vault v1.7.3-b131
[iConomy] Enabling iConomy v5.14
[VeinMiner] Enabling VeinMiner v1.17.10

**Comment by 2008Choco** [comment]
These are two separate issues.

1. There is no supported means to do this. However, in a future version, the `Name` and `Lore` settings will no longer function. This will be replaced with an NBT value. Obtaining this item, however, is beyond the scope of VeinMiner.
2. This cannot be confirmed in the upcoming version.

For the above reasons, I will close this issue and mark as "Resolved".
