### ISSUE TITLE
me want 1.19

### ISSUE THREAD

**Issue by WP2022OnYT** [2008Choco/VeinMiner#82]
1.19 when?

**Comment by 2008Choco** [comment]
VeinMiner on Bukkit supports 1.19 already. The Fabric client mod will receive an update in due time.

**Comment by Hikutaatti** [comment]
Indeed, please update to 1.19.
The plugin constantly keeps giving me notices to download the fabric mod which happens to still be on 1.18.

**Comment by 2008Choco** [comment]
The client-sided Fabric mod has been [updated to support 1.19](https://www.curseforge.com/minecraft/mc-mods/veinminer4bukkit/files/3900656). Sorry for the delay.
