### ISSUE TITLE
Clarification of "All" Category Under "BlockList" 

### ISSUE THREAD

**Issue by Yuogusy** [2008Choco/VeinMiner#84]
Apologies. I'm not sure if this is an actual issue or just a misunderstanding on my part. I am trying to reduce floating trees on my server by making VeinMiner work on any log when Shift is held down, regardless of what might be in the player's hand. I put all logs under the "All" category under BlockList, and I swore I tested it and it was working, but now it doesn't seem to. 

Does "All" imply that any hold-able block or item can be used, or does it just mean all "tools" plus an empty hand? Basically I want to see if I can set it up so that even if a player punches a tree with a block of dirt, it'll still VeinMine, as long as they hold shift.

If not, I can install a separate plugin for tree-felling, but I am trying to cut down on the number of plugins I have installed.

Thank you for the great plugin!

**Comment by 2008Choco** [comment]
The `All` category will add those blocks to all other categories (including the `Hand` category). It won't include any items that aren't already defined in a category. So,

> Does "All" imply that any hold-able block or item can be used
No

> does it just mean all "tools" plus an empty hand
Yes

I hope that answers your questions
