### ISSUE TITLE
Legacy versions

### ISSUE THREAD

**Issue by mohmedXM** [2008Choco/VeinMiner#86]
I couldn't download [VeinMiner 1.17.10](https://www.spigotmc.org/resources/veinminer.12038/update?update=454958) from spigot
Could you give me an extranal link or github link to the plugin.
It might be an issue for everyone who trying to download legacy versions, if you could edit it.

**Comment by 2008Choco** [comment]
Sorry about that. You should have been able to download those versions by looking at the Version History tab on Spigot, though I've adjusted the linked in the description to include (download) text which should directly download each file.
