### ISSUE TITLE
Suggestion: add toggle feature 

### ISSUE THREAD

**Issue by NBS-Paste** [2008Choco/VeinMiner#87]
I think if you could add a command like /veinminer off to allow us to toggle it off and in it would be nice. I had been working on a house and been crouching and accidentally broke half of my house’s frame.

**Comment by 2008Choco** [comment]
You can already do this with `/veinminer toggle`. If you're a server operator you can give players the permission `veinminer.command.toggle`. If you're a player, ask the server owner to give you this permission.

**Comment by NBS-Paste** [comment]
I had been meaning if you had the permission to use it you could turn it off or on when you wanted it.

**Comment by 2008Choco** [comment]
Again, this is possible with `/veinminer toggle` which is exactly what you were asking for in the original issue.
