### ISSUE TITLE
It wont let me do any commands.

### ISSUE THREAD

**Issue by ShadowChickens** [2008Choco/VeinMiner#9]
Hello. I am having problems with the veinminer commands. Im using 1.12 minecraft, and I cant get it to work. Im an operator and I type: /veinmier blocklist pickaxe add stone and it says "an internal error occured while trying to execute this command"
Can you help?

**Comment by 2008Choco** [comment]
What version of VeinMiner are you running (see `/veinminer version` or `/version veinminer`. Either will work)

**Comment by ShadowChickens** [comment]
1.12

**Comment by 2008Choco** [comment]
The naming scheme for VeinMiner is a bit strange and I apologize for that, but VeinMiner 1.12.x is for Minecraft 1.13.x. You should run instead VeinMiner 1.11.3 (downloadable [here](https://www.spigotmc.org/resources/veinminer.12038/update?update=163713))
