### ISSUE TITLE
Players cant vein mine when Worldguard is installed

### ISSUE THREAD

**Issue by Mooshed88** [2008Choco/VeinMiner#91]
Players (even ops) can not vein mine when Worldguard is installed. The message says "you are not allowed to vein mine in this area". How can I solve it? Thanks a lot.
![image](https://user-images.githubusercontent.com/110685419/213642436-04cfdb90-59fb-48f6-9abb-33f7067de733.png)

**Comment by KisaragiEffective** [comment]
I suppose you should give them proper permission or set region's flag (e.g. `block-break`)

**Comment by 2008Choco** [comment]
VeinMiner has an additional WorldGuard flag called `veinminer` which you can set to allow. Though the default unset value should allow players to do this. Keep this issue open and I'll consider it a bug.

**Comment by Mooshed88** [comment]
Thanks but... how can I set it to allow? When I use "/rg flag __global__ veinminer accept", it says "Unknown flag specified: veinminer".

**Comment by 2008Choco** [comment]
I cannot replicate this issue. To deny VeinMiner in a specific region, you should be able to run `/rg flag <region> veinminer deny` (or `allow` to allow it, although this is the default value).
