### ISSUE TITLE
Block break order is unexpected/out of order

### ISSUE THREAD

**Issue by KasaiSora** [2008Choco/VeinMiner#93]
There is a bug in VeinMiner, version 2.0.0, which allows players to dupe items.

If you have an axe at 1-4 durability, it will break when you try and mine a tree. And it will give you however many logs are in that tree, but will only destroy the block you mined. This will allow you to get more wood then is in the tree. This might also apply for ores, but we haven't checked.

Video showcasing the bug: https://youtu.be/7sqVZStd8Qc

**Comment by 2008Choco** [comment]
I don't believe this is a VeinMiner bug. VeinMiner doesn't do any item drops at all. Item drops are handled by vanilla Minecraft. All VM does is break the blocks and if the block break isn't successful then an item isn't dropped. What other plugins do you have installed?

**Comment by KasaiSora** [comment]
I have lots of plugins installed, but nothing that affects item drops that I know of. That's why we though it was VeinMiner, as it only happens when using the VeinMiner feature. Could it be a bug inside of Minecraft itself then?

List of my plugins: AdvancedRegionMarket, BeautyQuests, BetterRTP, ChestShop, Citizens, CoreProtect, DecentHolograms, Essentials, EssentialsChat, EssentialsSpawn, Graves, LuckPerms, Multiverse-Core, Multiverse-Inventories, NoMobGriefing, PlaceholderAPI, PlayTime*, TAB, Vault, VeinMiner, ViaVersion, WorldEdit, WorldGuard

**Comment by 2008Choco** [comment]
I can replicate this in the latest version but it doesn't seem to be a duplication bug. It's just breaking the blocks in an unexpected order. You'll notice in the video you sent that it broke the bottom block but it also broke the blocks from top to bottom.

Not a duplication glitch, but the break order can probably be refined.

**Comment by KasaiSora** [comment]
Oh alright well good to know what the cause is. Glad it's not a duplication thing. Didn't know the blocks at top of the tree did break :)

**Comment by 2008Choco** [comment]
I apologize for this issue being open for almost a year, but I've finally found time to return to update VeinMiner and I've fixed this issue in 8f16c4b. This will be fixed in VeinMiner 2.2.0!

**Comment by KasaiSora** [comment]
All good! Thanks for coming back to the issue and fixing it anyway!
